theme = "plain"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
format = "{percentage}%"

[[block]]
block = "time"
interval = 60
format = " %a %b %d %R"
